version: '3.3' 
services:
  www:
    build: .
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=decoracao
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8001:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306











